"use client";
import Link from "next/link";
import { apiMessages, friendlyError, readApiResponse } from "@/lib/api-response";
import { FormEvent, useEffect, useMemo, useState } from "react";
import type { PublicQuestion, Subject } from "@/lib/quiz-schema";
type QuizPayload = { date: string; subject: Subject; title: string; questions: PublicQuestion[] };
type Mark = { id: string; userAnswer: string; isCorrect: boolean; correctAnswer: string; explanation: string };
type Result = { score: number; total: number; results: Mark[] };

export default function QuizClient({ subject }: { subject: Subject }) {
  const [quiz, setQuiz] = useState<QuizPayload | null>(null), [answers, setAnswers] = useState<Record<string,string>>({}), [result, setResult] = useState<Result|null>(null);
  const [error, setError] = useState(""), [loading, setLoading] = useState(true), [submitting, setSubmitting] = useState(false), [attempt, setAttempt] = useState(0);
  useEffect(() => { const controller = new AbortController(); fetch(`/api/quiz/${subject}`, { signal: controller.signal }).then((response) => readApiResponse<QuizPayload>(response, apiMessages.QUIZ_UNAVAILABLE)).then(setQuiz).catch((e: unknown) => { if (e instanceof Error && e.name !== "AbortError") setError(friendlyError(e, apiMessages.QUIZ_UNAVAILABLE)); }).finally(() => setLoading(false)); return () => controller.abort(); }, [subject, attempt]);
  const answeredCount = useMemo(() => quiz?.questions.filter((q) => answers[q.id]?.trim()).length ?? 0, [answers, quiz]);
  const marksById = useMemo(() => new Map(result?.results.map((mark) => [mark.id, mark]) ?? []), [result]);
  async function submit(event: FormEvent) { event.preventDefault(); if (!quiz || answeredCount !== 10) { setError("Almost there! Please answer all 10 questions first."); return; } setSubmitting(true); setError(""); try { const response = await fetch(`/api/quiz/${subject}/submit`, { method:"POST", headers:{"Content-Type":"application/json"}, body:JSON.stringify({date:quiz.date,answers}) }); const data=await readApiResponse<Result>(response, apiMessages.GRADING_UNAVAILABLE); setResult(data); window.scrollTo({top:0,behavior:"smooth"}); } catch(e) { setError(friendlyError(e, apiMessages.GRADING_UNAVAILABLE)); } finally { setSubmitting(false); } }
  const name=subject==="math"?"Math":"Science", icon=subject==="math"?"➗":"🔬";
  return <main className={`quiz-shell ${subject}-theme`}><header className="quiz-header"><Link className="home-button" href="/">← Home</Link><div className="quiz-heading"><span>{icon}</span><div><p>DAILY P3 QUEST</p><h1>{name}</h1></div></div><div className="progress-pill">{answeredCount}/10 answered</div></header>
    {loading&&<section className="state-card"><div className="loader"/><h2>Making today’s fresh quiz…</h2><p>Our question robot is thinking carefully!</p></section>}
    {!loading&&error&&!quiz&&<section className="state-card error-card"><span>🌦️</span><h2>Oops, a small cloud!</h2><p>{error}</p><button onClick={()=>{setLoading(true);setError("");setAttempt((n)=>n+1)}}>Try again</button><Link href="/">Go home</Link></section>}
    {quiz&&<><section className="quiz-intro"><div><p className="date-label">SINGAPORE • {quiz.date}</p><h2>{result?"Quest complete!":quiz.title}</h2><p>{result?"Wonderful effort, Eira. Here is how you did!":"Answer every question, then submit your quest for marking."}</p></div>{result&&<div className="score-orb"><strong>{result.score}</strong><span>out of 10</span></div>}</section>
      {result&&<div className="result-actions"><Link href="/">⌂ Home</Link><button onClick={()=>document.getElementById("question-1")?.scrollIntoView({behavior:"smooth"})}>Review answers ↓</button></div>}{error&&<div className="inline-error" role="alert">{error}</div>}
      <form onSubmit={submit}><SectionHeading letter="A" title="Multiple Choice" note="Choose the best answer." />{quiz.questions.slice(0,6).map((q,i)=><QuestionCard key={q.id} question={q} number={i+1} answer={answers[q.id]||""} disabled={!!result} mark={marksById.get(q.id)} onAnswer={(v)=>setAnswers((old)=>({...old,[q.id]:v}))}/>)}<SectionHeading letter="B" title="Structured Answer" note="Type a short, clear answer." />{quiz.questions.slice(6).map((q,i)=><QuestionCard key={q.id} question={q} number={i+7} answer={answers[q.id]||""} disabled={!!result} mark={marksById.get(q.id)} onAnswer={(v)=>setAnswers((old)=>({...old,[q.id]:v}))}/>)}{!result&&<div className="submit-area"><p>{answeredCount===10?"All ready — you’ve got this! 🌟":`${10-answeredCount} question${10-answeredCount===1?"":"s"} left to answer`}</p><button className="submit-button" disabled={submitting}>{submitting?"Marking…":"Submit my quest ✨"}</button></div>}</form></>}
  </main>;
}
function SectionHeading({letter,title,note}:{letter:string;title:string;note:string}) { return <div className="section-heading"><span>Section {letter}</span><div><h2>{title}</h2><p>{note}</p></div></div>; }
function QuestionCard({question,number,answer,disabled,mark,onAnswer}:{question:PublicQuestion;number:number;answer:string;disabled:boolean;mark?:Mark;onAnswer:(v:string)=>void}) { return <article id={`question-${number}`} className={`question-card ${mark?(mark.isCorrect?"correct":"incorrect"):""}`}><div className="question-top"><span className="question-number">{number}</span><span className="topic-chip">{question.topic}</span>{mark&&<span className="mark-badge">{mark.isCorrect?"✓ Correct":"✕ Try again"}</span>}</div><p className="question-prompt">{question.prompt}</p>{question.type==="mcq"?<div className="choices">{question.choices.map((choice,i)=><label key={choice} className={answer===choice?"selected":""}><input type="radio" name={question.id} value={choice} checked={answer===choice} disabled={disabled} onChange={()=>onAnswer(choice)}/><span className="choice-letter">{String.fromCharCode(65+i)}</span><span>{choice}</span></label>)}</div>:<input className="short-answer" aria-label={`Answer for question ${number}`} placeholder="Type your answer here…" value={answer} disabled={disabled} onChange={(e)=>onAnswer(e.target.value)}/>} {mark&&<div className="explanation"><strong>{mark.isCorrect?"Great thinking!":`Correct answer: ${mark.correctAnswer}`}</strong><p>{mark.explanation}</p>{!mark.isCorrect&&<small>Your answer: {mark.userAnswer}</small>}</div>}</article>; }
